### ISSUE TITLE
Wiederholte Kurserstellung schlägt fehl

### ISSUE THREAD

**Issue by Flavia-de-Luce** [Summit-Sync/backend#45]
Ich bin mir nicht ganz sicher wie es zustande kommt, aber ich habe von einem Template 2 Kurse erfolgreich erstellt.
Bei dem dritten bekomme ich einen 500er Internal Server Error...

Aus dem folgenden Stacktrace habe ich entnehmen können das es bei der Vergabe des Kurskürzels passiert (Auzug aus ST):

`api-1    | 2024-05-31T09:54:52.548Z DEBUG 1 --- [nio-8080-exec-8] o.s.web.servlet.DispatcherServlet        : Failed to complete request: java.lang.NumberFormatException: For input string: "KM002"        
api-1    | 2024-05-31T09:54:52.548Z ERROR 1 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NumberFormatException: For input string: "KM002"] with root cause`

Ich glaube das das problem entsteht weil ich bereits einen Kurs mit "KM002" hatte:
![image](https://github.com/Summit-Sync/backend/assets/76540879/a5ebf6dd-d4d3-44c1-bdb9-08b09288e964)

Mir ist noch aufgefallen das alle, im Nachhinein bearbeiteten Kurse, ihre courseNumber auf "1" gesetzt bekommen:
![image](https://github.com/Summit-Sync/backend/assets/76540879/54ba14cb-316b-44a6-bb06-2a7aae71b037)

Hier der gesamte Stacktrace des Calls, falls das hilft:
`api-1    | 2024-05-31T09:54:52.514Z DEBUG 1 --- [nio-8080-exec-8] o.s.web.client.DefaultRestClient         : Reading to [com.summitsync.api.keycloak.dto.KeycloakUser]
api-1    | 2024-05-31T09:54:52.516Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select t1_0.trainer_id,t1_0.subject_id from ss_trainer t1_0 where t1_0.trainer_id=?
api-1    | 2024-05-31T09:54:52.516Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
api-1    | 2024-05-31T09:54:52.521Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : insert into ss_course_template_price (name,price,course_template_price_id) values (?,?,?)     
api-1    | 2024-05-31T09:54:52.522Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:VARCHAR) <- [Anfänger]
api-1    | 2024-05-31T09:54:52.522Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (2:NUMERIC) <- [200]
api-1    | 2024-05-31T09:54:52.522Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (3:BIGINT) <- [23]
api-1    | 2024-05-31T09:54:52.526Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : insert into ss_course_template_price (name,price,course_template_price_id) values (?,?,?)     
api-1    | 2024-05-31T09:54:52.526Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:VARCHAR) <- [Götter]
api-1    | 2024-05-31T09:54:52.526Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (2:NUMERIC) <- [5]
api-1    | 2024-05-31T09:54:52.526Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (3:BIGINT) <- [24]
api-1    | 2024-05-31T09:54:52.529Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select l1_0.location_id,l1_0.city,l1_0.country,l1_0.email,l1_0.maps_url,l1_0.phone,l1_0.post_code,l1_0.street,l1_0.title from ss_location l1_0 where l1_0.location_id=?
api-1    | 2024-05-31T09:54:52.530Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
api-1    | 2024-05-31T09:54:52.532Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select q1_0.qualification_id,q1_0.name from ss_qualification q1_0 where q1_0.qualification_id=?
api-1    | 2024-05-31T09:54:52.532Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
api-1    | 2024-05-31T09:54:52.536Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select c1_0.course_id,c1_0.acronym,c1_0.cancelled,c1_0.course_number,c1_0.description,c1_0.dur
ation,c1_0.finished,c1_0.location_location_id,c1_0.meeting_point,c1_0.notes,c1_0.number_participants,c1_0.number_trainer,c1_0.number_waitlist,c1_0.title,c1_0.visible from ss_course c1_0 where c1_0.acronym=? order by c1_0.course_number desc
api-1    | 2024-05-31T09:54:52.536Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:VARCHAR) <- [KM]
api-1    | 2024-05-31T09:54:52.538Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select t1_0.course_id,t1_1.trainer_id,t1_1.subject_id from ss_course_trainer_join t1_0 join ss_trainer t1_1 on t1_1.trainer_id=t1_0.trainer_id where t1_0.course_id=?
api-1    | 2024-05-31T09:54:52.538Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
api-1    | 2024-05-31T09:54:52.539Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select rq1_0.course_id,rq1_1.qualification_id,rq1_1.name from ss_course_required_qualifications_join rq1_0 join ss_qualification rq1_1 on rq1_1.qualification_id=rq1_0.qualification_id where rq1_0.course_id=?
api-1    | 2024-05-31T09:54:52.539Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
api-1    | 2024-05-31T09:54:52.540Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select ct1_0.course_course_id,ct1_0.course_trainer_id,s1_0.status_id,s1_0.text,ct1_0.trainer_trainer_id from ss_course_trainer ct1_0 left join ss_status s1_0 on s1_0.status_id=ct1_0.status_status_id where ct1_0.course_course_id=?
api-1    | 2024-05-31T09:54:52.540Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
api-1    | 2024-05-31T09:54:52.541Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select a1_0.course_course_id,a1_0.application_id,a1_0.accepted,g1_0.group_id,g1_0.acronym,g1_0
.cancelled,g1_0.contact_contact_id,g1_0.description,g1_0.duration,g1_0.group_number,l1_0.location_id,l1_0.city,l1_0.country,l1_0.email,l1_0.maps_url,l1_0.phone,l1_0.post_code,l1_0.street,l1_0.title,g1_0.
meeting_point,g1_0.number_of_dates,g1_0.number_participants,g1_0.participants_per_trainer,g1_0.price_per_participant,g1_0.title,g1_0.total_price,g1_0.trainer_price_per_hour,t1_0.trainer_id,t1_0.subject_i
d from ss_trainer_application a1_0 left join ss_group g1_0 on g1_0.group_id=a1_0.group_group_id left join ss_location l1_0 on l1_0.location_id=g1_0.location_location_id left join ss_trainer t1_0 on t1_0.trainer_id=a1_0.trainer_trainer_id where a1_0.course_course_id=?
api-1    | 2024-05-31T09:54:52.541Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
api-1    | 2024-05-31T09:54:52.542Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select t1_0.course_id,t1_1.trainer_id,t1_1.subject_id from ss_course_trainer_join t1_0 join ss_trainer t1_1 on t1_1.trainer_id=t1_0.trainer_id where t1_0.course_id=?
api-1    | 2024-05-31T09:54:52.543Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
api-1    | 2024-05-31T09:54:52.543Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select rq1_0.course_id,rq1_1.qualification_id,rq1_1.name from ss_course_required_qualifications_join rq1_0 join ss_qualification rq1_1 on rq1_1.qualification_id=rq1_0.qualification_id where rq1_0.course_id=?
api-1    | 2024-05-31T09:54:52.544Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
api-1    | 2024-05-31T09:54:52.545Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select ct1_0.course_course_id,ct1_0.course_trainer_id,s1_0.status_id,s1_0.text,ct1_0.trainer_trainer_id from ss_course_trainer ct1_0 left join ss_status s1_0 on s1_0.status_id=ct1_0.status_status_id where ct1_0.course_course_id=?
api-1    | 2024-05-31T09:54:52.545Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
api-1    | 2024-05-31T09:54:52.546Z DEBUG 1 --- [nio-8080-exec-8] org.hibernate.SQL                        : select a1_0.course_course_id,a1_0.application_id,a1_0.accepted,g1_0.group_id,g1_0.acronym,g1_0
.cancelled,g1_0.contact_contact_id,g1_0.description,g1_0.duration,g1_0.group_number,l1_0.location_id,l1_0.city,l1_0.country,l1_0.email,l1_0.maps_url,l1_0.phone,l1_0.post_code,l1_0.street,l1_0.title,g1_0.
meeting_point,g1_0.number_of_dates,g1_0.number_participants,g1_0.participants_per_trainer,g1_0.price_per_participant,g1_0.title,g1_0.total_price,g1_0.trainer_price_per_hour,t1_0.trainer_id,t1_0.subject_i
d from ss_trainer_application a1_0 left join ss_group g1_0 on g1_0.group_id=a1_0.group_group_id left join ss_location l1_0 on l1_0.location_id=g1_0.location_location_id left join ss_trainer t1_0 on t1_0.trainer_id=a1_0.trainer_trainer_id where a1_0.course_course_id=?
api-1    | 2024-05-31T09:54:52.546Z TRACE 1 --- [nio-8080-exec-8] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [2]
api-1    | 2024-05-31T09:54:52.548Z DEBUG 1 --- [nio-8080-exec-8] o.s.web.servlet.DispatcherServlet        : Failed to complete request: java.lang.NumberFormatException: For input string: "KM002"        
api-1    | 2024-05-31T09:54:52.548Z ERROR 1 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NumberFormatException: For input string: "KM002"] with root cause
api-1    |
api-1    | java.lang.NumberFormatException: For input string: "KM002"
api-1    |      at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[na:na]
api-1    |      at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[na:na]
api-1    |      at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[na:na]
api-1    |      at com.summitsync.api.course.CourseService.generateCourseNumber(CourseService.java:46) ~[!/:0.0.1-SNAPSHOT]
api-1    |      at com.summitsync.api.course.CourseService.create(CourseService.java:40) ~[!/:0.0.1-SNAPSHOT]
api-1    |      at com.summitsync.api.course.CourseController.addCourse(CourseController.java:36) ~[!/:0.0.1-SNAPSHOT]
api-1    |      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
api-1    |      at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
api-1    |      at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:261) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:189) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917) ~[spring-webmvc-6.1.3.jar!/:6.1.3]        
api-1    |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.18.jar!/:na]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.2.1.jar!/:6.2.1] 
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:145) ~[spring-security-oauth2-resource-server-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195) ~[spring-webmvc-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:225) ~[spring-security-config-6.2.1.jar!/:6.2.1]
api-1    |      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar!/:na]
api-1    |      at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
/json, application/*+json]
api-1    | 2024-05-31T09:54:52.553Z DEBUG 1 --- [nio-8080-exec-8] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Writing [{timestamp=Fri May 31 09:54:52 UTC 2024, status=500, error=Internal Server Error, path=/api/v1/cours (truncated)...]
api-1    | 2024-05-31T09:54:52.554Z DEBUG 1 --- [nio-8080-exec-8] o.s.web.servlet.DispatcherServlet        : Exiting from "ERROR" dispatch, status 500
db-1     | 2024-05-31 09:56:32.034 UTC [27] LOG:  checkpoint starting: time
db-1     | 2024-05-31 09:56:33.062 UTC [27] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.009 s, sync=0.010 s, total=1.029 s; sync files=11, longest=0.005 s, average=0.001 s; distance=11 kB, estimate=30 kB; lsn=0/1A542E0, redo lsn=0/1A542A8`

**Comment by onestay** [comment]
1d9c4f702140e41c5591b61efded89a369969c85
