### ISSUE TITLE
Gruppen absagen

### ISSUE THREAD

**Issue by Flavia-de-Luce** [Summit-Sync/backend#48]
Wenn man eine Gruppe via
`http://localhost:8080/api/v1/course/${id}/cancel`
absagt dann gilt der Call als erfolgreich, der Wert wird aber nicht weggeschrieben...

Canceln:
![image](https://github.com/Summit-Sync/backend/assets/76540879/7d4419da-83f0-4f65-9def-86656f35e4a4)
![image](https://github.com/Summit-Sync/backend/assets/76540879/1ad553e0-f000-4b2d-b2a6-c0a307145d28)
![image](https://github.com/Summit-Sync/backend/assets/76540879/9e347b2c-ba7b-41cd-8108-cd0bd5774a03)

getAllGroups:
![image](https://github.com/Summit-Sync/backend/assets/76540879/360c0134-098f-4d88-8aa6-2ca72a08e462)

**Comment by onestay** [comment]
fixed 88b38bef90bc39aad78222c3f1bd4599b0340640
