### ISSUE TITLE
Kurse absagen

### ISSUE THREAD

**Issue by Flavia-de-Luce** [Summit-Sync/backend#49]
Beim absagen von Kursen bekommt man einen 400 (Bad Request):

![image](https://github.com/Summit-Sync/backend/assets/76540879/506d2b75-9a2e-40aa-915c-b42a900dd083)

![image](https://github.com/Summit-Sync/backend/assets/76540879/66d82817-50d7-4492-8919-c203c0fbd2a0)

**Comment by onestay** [comment]
fixed 6ddbbafd1f213af71698cd6088e48a93af1524f5
