### ISSUE TITLE
Standort löschen geht nicht (Verletzung von Constraints)

### ISSUE THREAD

**Issue by jan-okke** [Summit-Sync/backend#54]
org.postgresql.util.PSQLException: ERROR: update or delete on table "ss_qualification" violates foreign key constraint "fk8fhxmjvcpoq6efp5pxc58ii3v" on table "ss_trainer_qualification_join"
api-1    |   Detail: Key (qualification_id)=(1) is still referenced from table "ss_trainer_qualification_join".

**Comment by jan-okke** [comment]
gleiches für Gruppenvorlage (Kursvorlage funktioniert)

**Comment by onestay** [comment]
Kann ich nicht reproducen. Bist du dir bei Location (obwohl in den Fehler qualification steht) sicher, dass sie nicht mehr referenziert wird, von irgendeinen Kurs, Group oder Template?
